# Generated by Django 5.2.12 on 2026-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0031_add_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this game instance is active (visible to regular users); inactive instances are hidden from users but preserved for mod history'),
        ),
        migrations.AddField(
            model_name='historicalgameinstance',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this game instance is active (visible to regular users); inactive instances are hidden from users but preserved for mod history'),
        ),
    ]
