# Generated by Django 5.2.12 on 2026-08-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0032_gameinstance_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallinkedaccount",
            name="verified",
            field=models.BooleanField(
                default=True, help_text="DEPRECATED: always True; an active link is what makes an account verified (use 'active' instead)"
            ),
        ),
        migrations.AlterField(
            model_name="linkedaccount",
            name="verified",
            field=models.BooleanField(
                default=True, help_text="DEPRECATED: always True; an active link is what makes an account verified (use 'active' instead)"
            ),
        ),
    ]
